language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - chmod +x ./tests/run-tests.sh

script: VERBOSE=true ./tests/run-tests.sh -s tests/
